name: Deploy Dev Environment
on:
  push:
    branches: [ "main", "develop", "release/**" ]

permissions:
  id-token: write
  contents: read

jobs:
  CheckPendingWorkflow:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-queue@542658b3a8270cac81ae15d401b0d974732808ac # v1
        with:
          delay: 300000
          timeout: 7200000
  DeployLISA:
    needs: CheckPendingWorkflow
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@cf459bd40262a8603163308e488de922e4eb5a95 # v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/${{ vars.ROLE_NAME_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-duration-seconds: 14400
      - name: Create config-custom.yaml
        id: create-yaml
        run: |
          echo "${{vars.CONFIG_YAML}}" > config-custom.yaml
      - name: Set up Python 3.13
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v5
        with:
          python-version: "3.13"
      - name: Use Node.js 24.x
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v4
        with:
          node-version: 24.x
      - name: Install CDK dependencies
        run: |
          npm ci
      - name: Deploy LISA
        run: |
          make deploy HEADLESS=true
  SendSlackNotification:
    name: Send Slack Notification
    needs: [ DeployLISA ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Notification that Dev Deploy Finished
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ contains(join(needs.*.result, ' '), 'failure') && 'failure' || 'success' }}
          SLACK_TITLE: 'Dev Deploy Finished'
          SLACK_FOOTER: ''
          MSG_MINIMAL: 'actions url,commit'
          SLACK_MESSAGE_ON_FAILURE: '<!here> Dev Deploy FAILED on branch ${{ github.head_ref || github.ref_name }} for <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|commit>'
          SLACK_MESSAGE_ON_SUCCESS: 'Dev Deploy SUCCESS on branch ${{ github.head_ref || github.ref_name }} for <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|commit>.'
          SLACK_MESSAGE: 'Dev Deploy Finished with status ${{ job.status }} on branch ${{ github.head_ref || github.ref_name }} for <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|commit>'
